const Groq = require("groq-sdk");
require('dotenv').config();

class LlmService {
    constructor() {
        this.client = null;
        this.initialized = false;
        this.model = "llama-3-8b-8192"; // Super fast and free on Groq
    }

    async initialize() {
        if (this.initialized) return;

        try {
            const apiKey = process.env.GROQ_API_KEY;
            if (!apiKey) {
                console.warn("GROQ_API_KEY is missing. LLM features will not work.");
                return;
            }

            this.client = new Groq({
                apiKey: apiKey
            });

            this.initialized = true;
            console.log("Groq LLM Service initialized successfully.");
        } catch (error) {
            console.error("Failed to initialize Groq client:", error);
            throw error;
        }
    }

    async generateSql(userQuestion) {
        if (!this.initialized) await this.initialize();

        if (!this.client) {
            throw new Error("LLM Service not initialized. Please check GROQ_API_KEY.");
        }

        const schema = `
Tables in the database:

1. speed_tests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    test_id VARCHAR(36) UNIQUE,
    download_mbps DECIMAL(10, 2),
    upload_mbps DECIMAL(10, 2),
    latency_ms INT,
    jitter_ms INT,
    network_type ENUM('2G','3G', '4G', '5G'),
    signal_strength_dbm INT,
    operator VARCHAR(50) DEFAULT 'Mobilis',
    device_type VARCHAR(50),
    wilaya VARCHAR(50),
    commune VARCHAR(50),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
)

2. bts_antennas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100),
    wilaya VARCHAR(50),
    commune VARCHAR(50),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    etatA ENUM('actif', 'inactif', 'maintenance'),
    etatB ENUM('actif', 'inactif', 'maintenance'),
    etatC ENUM('actif', 'inactif', 'maintenance'),
    date_installation DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
`;

        const systemPrompt = `
You are an expert SQL assistant for the 'mobilis_dashboard' database.
${schema}

RULES:
1. Return ONLY the SQL query. No explanations, no markdown code blocks.
2. Use EXACT table and column names.
3. If unanswerable, return: "ERROR: This question cannot be answered using the available database tables."
4. Ensure MySQL syntax.
`;

        try {
            console.log("Requesting SQL from Groq...");
            const chatCompletion = await this.client.chat.completions.create({
                messages: [
                    { role: "system", content: systemPrompt },
                    { role: "user", content: userQuestion }
                ],
                model: this.model,
                temperature: 0.1, // Low temperature for consistent SQL
            });

            let sql = chatCompletion.choices[0]?.message?.content || "";

            // Cleanup in case the LLM still adds backticks
            sql = sql.replace(/```sql/g, '').replace(/```/g, '').trim();

            console.log("SQL generated by Groq:", sql);
            return sql;
        } catch (error) {
            console.error("Error generating SQL via Groq:", error);
            throw error;
        }
    }
}

module.exports = new LlmService();
